### ISSUE TITLE
Argonaut-server does not start after reboot on RHEL/CentOS

### ISSUE THREAD

**Issue by papertray3** [fusiondirectory/argonaut#1]
There is a typo in the argonaut-server.service file:
[Install]
WantedBy=muli-user.target

should be:
[Install]
WantedBy=multi-user.target

**Comment by papertray3** [comment]
Looks like the same issue exists in the argonaut-client.service file too.

**Comment by bilbo-the-hobbit** [comment]
hello,

good catch, thanks for the report, i have opened issue https://forge.fusiondirectory.org/issues/4691, will be corrected in Argonaut 0.9.7

Cheers

**Comment by bilbo-the-hobbit** [comment]
fixed in https://git.fusiondirectory.org/?p=main/argonaut.git;a=commit;h=db504c492cd451e267484043fcfd2f52caf68994

Cheers
